- name: manage RRWG deployment
  connection: local
  hosts: localhost
  become: yes
  vars:
    binpath: "/tmp/rrwg"
  tasks:
    - name: install dependencies
      pip:
        name:
          - matplotlib
      tags: install

    - name: copy files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dst }}"
        mode: "{{ item.mod }}"
      loop:
        - {src: rrwg.py, dst: "{{ binpath }}", mod: '775'}
      tags: install

    - name: remove files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ binpath }}"
      tags: uninstall
